export enum SortBy {
  PERCENTAGE = "PERCENTAGE",
  MARKET_CAP_RANK = "MARKET_CAP_RANK",
  CURRENT_PRICE = "CURRENT_PRICE",
  MAX_SUPPLY = "MAX_SUPPLY",
  CHANGE_PRICE_IN_24H = "CHANGE_PRICE_IN_24H",
  CHANGE_PRICE_IN_7D = "CHANGE_PRICE_IN_7D",
  CHANGE_PRICE_IN_30D = "CHANGE_PRICE_IN_30D"
}