export enum SortBy {
  PERCENTAGE = "PERCENTAGE",
  CURRENT_PRICE = "CURRENT_PRICE",
  CHANGE_PRICE_IN_24H = "CHANGE_PRICE_IN_24H",
  CHANGE_PRICE_IN_7D = "CHANGE_PRICE_IN_7D",
  CHANGE_PRICE_IN_30D = "CHANGE_PRICE_IN_30D"
}